channels:
- conda-forge
dependencies:
- python=3.9.2
- pip<=25.1.1
- pip:
  - mlflow==3.1.0
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.12.0
  - xgboost==2.1.4
name: mlflow-env
